services:
  gateway-server:
    image: gateway-server:latest
    container_name: gateway-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend-net

networks:
  backend-net:
    external: true
